// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'Your Api key',
    appId: '1:600065728239:web:1b6f539599918f96fb451a',
    messagingSenderId: '600065728239',
    projectId: 'chat-app-543',
    authDomain: 'chat-app-543.firebaseapp.com',
    storageBucket: 'chat-app-543.appspot.com',
    measurementId: 'G-X3HZFCEVR4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRgXOHVMHRhTMC3wSthzezkyJSfvakaiE',
    appId: '1:600065728239:android:b63d684d2025af5afb451a',
    messagingSenderId: '600065728239',
    projectId: 'chat-app-543',
    storageBucket: 'chat-app-543.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlPOyVK9AVjksYgmpx9-44VEhkG33NEts',
    appId: '1:600065728239:ios:62af0a62e67d3119fb451a',
    messagingSenderId: '600065728239',
    projectId: 'chat-app-543',
    storageBucket: 'chat-app-543.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlPOyVK9AVjksYgmpx9-44VEhkG33NEts',
    appId: '1:600065728239:ios:f6ff9cfdfca4acd3fb451a',
    messagingSenderId: '600065728239',
    projectId: 'chat-app-543',
    storageBucket: 'chat-app-543.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
